CREATE TABLE orgao (
  id UUID PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  acronimo VARCHAR(255),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);